# Object Oriented Programming
## Practice Problems

### 1. Create a class called `Book` that has the attributes `title`, `author`, `pages`, `price`. It also has the method `get_price()` which returns `price`. Then create two instances of this class:

- `b1`:
`title` -> 'Practical Programming...'
`author` -> 'Gries, Campbell, Montojo'
`pages` -> 383
`price` -> 50

- `b2`:
`title` -> 'Building a Career in Data Science'
`author` -> 'Robinson, Nolis'
`pages` -> 322
`price` -> 40

In [14]:
# Your code goes here
class Book:
    def __init__(book,title,author,pages,price):
      book.title = title
      book.author = author
      book.pages = pages
      book.price = price
      
    def get_price(book):
      return book.price

b1 = Book('Practical Programming','Gries, Campbell, Montojo','383','50')
print('The book author names are ' + b1.author)
print('The book price is ' + b1.get_price())

b2 = Book('Building a Career in Data Science','Robinson, Nolis','322','40')
print('The book names is ' + b2.title)
print('The book price is ' + b2.get_price())

The book author names are Gries, Campbell, Montojo
The book price is 50
The book names is Building a Career in Data Science
The book price is 40

<details>
  <summary>Answer</summary>

  ```python
  class Book:
  def __init__(self, title, author, pages, price):
    self.title = title
    self.author = author
    self.pages = pages
    self.price = price

  def get_price(self):
    return self.price

  b1 = Book('Practical Programming...', 'Gries, Campbell, Montojo', 383, 50)
  b2 = Book('Building a Career in Data Science', 'Robinson, Nolis', 322, 40)

  print(b1.getprice())
  ```
</details>

### 2. Create a `Phone` class that has the attributes `model`, `id`, `name`, `brand` and `price`. Create the getters and setters for each attribute. As well as the following methods: `calculate_total` which takes the price and calculates it by the tax argument.

In [26]:
# Your code goes here
class Phone:
    def __init__(self,model,id,name,brand,price):
        self.model = model
        self.id = id
        self.name = name
        self.brand = brand
        self.price = price
    
    def calculate_total(self):
        ont_tax= 1.13
        total_price = self.price * ont_tax
        return total_price
    
p1 = Phone(2024,2.0,'sonata','hyndai',35000)
print('car name is ' + p1.name)
print(p1.model)
print(p1.calculate_total())
print('total price of ' +p1.name + ' is ' + str(p1.calculate_total()))

car name is sonata
2024
39549.99999999999
total price of sonata is 39549.99999999999

<details>
  <summary>Answer</summary>

  ```python
  class Phone:
    def __init__(self, model, id, name, brand, price):
      self._model = model
      self._id = id
      self._name = name
      self._brand = brand
      self._price = price
    
    def calculate_total(self, tax):
      return self._price * tax
    
  phone = Phone("15 Pro Max", 1, "iPhone", "Apple", 1599)
  print(phone.calculate_total(1.13))
  ```
</details>